### ISSUE TITLE
Tags with multiple not-quoted attributes are not being properly extracted.

### ISSUE THREAD

**Issue by gushuro** [emmetio/extract-abbreviation#2]
When extracting an abbreviation where a child element has multiple attributes that are not quoted, part of it is wrongly identified as an html tag. Therefore, it fails to extract the whole abbreviation.

Example:
`isAtHTMLTag(new StreamReader('div[foo=bar foo2=bar2]>'))` returns true.

Therefore, when trying to extract abbreviation from something like `div[foo=bar foo2=bar2]>ul ` and then expand it we get `div[foo=bar foo2=bar2]><ul></ul>` instead of
```
<div foo="bar" foo2="bar2">
	<ul></ul>
</div>
```

**Comment by ramya-rao-a** [comment]
Thanks @gushuro!
@sergeche Can you take a look please?

**Comment by ramya-rao-a** [comment]
This got fixed with #3
